### ISSUE TITLE
Significant increase in memory usage from previous versions

### ISSUE THREAD

**Issue by Andon-A** [adafruit/Adafruit-ST7735-Library#51]
This bears particular interest to myself due to the fact that I'm using a ST7735R screen with my [Digibadge Mini](https://github.com/PhoenixbornTech/DigiBadge_Mini), and with that project I'm pushing the ATMega328p to its absolute maximums.

The older version of the library that I have been using is the version 1.0.8 - After this, the Arduino library manager didn't see that the "ST7735 and ST7789" library was formerly known as the "ST7735" library. A user notified me that they were unable to get the program to compile.

I took a look and updated all of my libraries, and after updating this library to 1.2.1, I found that it was using an additional 1074 bytes over what it had been using in 1.0.8.

A basic progam, written below, uses 8792 bytes of memory using version 1.2.1 and 1.2.0. It uses 7805 in 1.1.0 and 7764 in 1.0.8 
```#include <Adafruit_GFX.h>
#include <Adafruit_ST7735.h>


Adafruit_ST7735 tft = Adafruit_ST7735(10, 9, -1);

void setup() {
  // put your setup code here, to run once:
  tft.initR(INITR_BLACKTAB);
  tft.fillScreen(ST7735_BLACK);

}

void loop() {
  // put your main code here, to run repeatedly:
  delay(100);
}```

With a memory usage increase of about 13% between 1.1 and 1.2, I'm wondering if it would be possible to have some define set to choose between speed and memory compactness.

**Comment by ladyada** [comment]
hiya, yep this is likely due to us making a huge refactor so that ST77xx now is a subclass of Adafruit_SPITFT, all that SPI management is now moved there, where it has been heavily optimized. that means there's another layer of code - but we are going to be able to do stuff like DMA for the samd21, '51 and other chips with DMA support
your best bet is ilkely to tell people to install the earlier version of the library when compiling!
